server:
  port: 8088
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password: password
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        show_sql: true
        format_sql: true